// Fyleria Engine
// Copyright © 2019 Go Go Gecko Productions

// Internal includes
#include "CharacterData/CharacterActionData.h"
#include "CharacterData/CharacterBasicData.h"
#include "CharacterData/CharacterBattleData.h"
#include "CharacterData/CharacterProgressData.h"
#include "CharacterData/CharacterSkillData.h"
#include "CharacterData/CharacterStatChangeData.h"
#include "CharacterData/CharacterMediaData.h"
#include "Utility/Macros.h"
#include "Utility/Python.h"

PYBIND11_MAKE_OPAQUE(Gecko::CharacterActionDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterBasicDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterBattleDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterProgressDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterSkillDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterStatChangeDataArray);

PYBIND11_EMBEDDED_MODULE(GeckoCharacterData, m)
{
    // CharacterActionData.h
    PyBindClass<Gecko::CharacterActionData>(m, "CharacterActionData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterActionData)
        WRAPPING_ADD_METHOD_SIMPLE(UpdateAvailableActions, Gecko::CharacterActionData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyActionCost, Gecko::CharacterActionData)
        WRAPPING_ADD_METHOD_SIMPLE(UpdateAvailableAP, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(SlashPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(SeverPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(SlicePoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(SlitPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CleavePoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(DecapitatePoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ParryPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(RipostePoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(BashPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(SmashPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ImpactPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CrushPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(BreakPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CrackPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(BlockPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(RushPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PiercePoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(DrillPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ShootPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ImpalePoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(StealthStrikePoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CriticalShotPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(DodgePoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CounterPoints, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(AvailableActions, Gecko::CharacterActionData)
    ;
    PyBindVector<Gecko::CharacterActionDataArray>(m, "CharacterActionDataArray");

    // CharacterBasicData.h
    PyBindClass<Gecko::CharacterBasicData>(m, "CharacterBasicData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CharacterID, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PartyID, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(FirstName, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(LastName, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Gender, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Hair, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Eyes, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Handedness, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(BaseRace, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(TransformedRace, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PowerSet, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(WeaponSet, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Age, Gecko::CharacterBasicData)
    ;
    PyBindVector<Gecko::CharacterBasicDataArray>(m, "CharacterBasicDataArray");

    // CharacterBattleData.h
    PyBindClass<Gecko::CharacterBattleData>(m, "CharacterBattleData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyNewStatus, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyGivenDamage, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyTakenDamage, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(AdvanceRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(FinishBattle, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(CanRegenerateFromStat, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(UpdateEquipmentRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(ResolveTargetPlaceholder, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(GetPrimaryWeaponRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(GetSecondaryWeaponRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(GetPrimaryShieldRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(GetSecondaryShieldRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionSourceThisAction, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(MostRecentActionSource, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PreviousActionTypes, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionTargetsThisAction, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionTargetsThisRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionTargetsLastRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionSourcesThisRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionSourcesLastRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(MostRecentActionTargets, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(IsDead, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(IsUnconscious, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(AttackCounter, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(DefendCounter, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(DamageTakenThisRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(DamageTakenThisBattle, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(DamageGivenThisRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(DamageGivenThisBattle, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(AllowedTargetAmount, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedWeaponLeftBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedWeaponLeftPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedWeaponLeftSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedWeaponRightBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedWeaponRightPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedWeaponRightSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedShieldLeftBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedShieldLeftPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedShieldLeftSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedShieldLeftMagicRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedShieldRightBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedShieldRightPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedShieldRightSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedShieldRightMagicRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedArmorBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedArmorPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedArmorSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedArmorMagicRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ChanceToCauseCriticalHit, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ChanceToBlockCriticalHit, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CriticalHitMultiplier, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ChanceToApplyMultipleAttacks, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(AttacksMultiplier, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(WeaponPrimaryDamageBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(WeaponPrimaryDamageBonusPercent, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(WeaponSecondaryDamageBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(WeaponSecondaryDamageBonusPercent, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(GeneralDamageBonusPercent, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(GeneralDamageBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(DefensivePowerEffectsBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(DefensivePowerEffectsBonusPercent, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(OffensivePowerEffectsBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(OffensivePowerEffectsBonusPercent, Gecko::CharacterBattleData)
    ;
    PyBindVector<Gecko::CharacterBattleDataArray>(m, "CharacterBattleDataArray");

    // CharacterProgressData.h
    PyBindClass<Gecko::CharacterProgressData>(m, "CharacterProgressData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterProgressData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyTakenDamage, Gecko::CharacterProgressData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyRegeneration, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(HealthPointsCurrent, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(MagicPointsCurrent, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EnergyPointsCurrent, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(HealthPointsMax, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(MagicPointsMax, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EnergyPointsMax, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(HealthRegen, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(MagicRegen, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EnergyRegen, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(HealthCostDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(MagicCostDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EnergyCostDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Speed, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(AmberValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(RubyValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(DiamondValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CitrineValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(OnyxValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(QuartzValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(SapphireValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(AmethystValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EmeraldValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(GarnetValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(IvoryValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(OpalValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(BluntAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(BluntDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(MagicAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(MagicDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PierceAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PierceDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(SlashAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(SlashDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EnergyAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EnergyDefense, Gecko::CharacterProgressData)
    ;
    PyBindVector<Gecko::CharacterProgressDataArray>(m, "CharacterProgressDataArray");

    // CharacterSkillData.h
    PyBindClass<Gecko::CharacterSkillData>(m, "CharacterSkillData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterSkillData)
        WRAPPING_ADD_METHOD_SIMPLE(GetSkillCurrentValue, Gecko::CharacterSkillData)
        WRAPPING_ADD_METHOD_SIMPLE(GetSkillRankValue, Gecko::CharacterSkillData)
        WRAPPING_ADD_METHOD_SIMPLE(UpdateSkillValue, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Barbarian, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Mage, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Rogue, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Blademaster, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Avatar, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Ambidextrous, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Focused, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Stalwart, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Slash, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Sever, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Slice, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Slit, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Cleave, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Decapitate, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Parry, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Riposte, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Bash, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Smash, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Crush, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Impact, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Break, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Crack, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Block, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Rush, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Pierce, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Drill, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Shoot, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Impale, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(StealthStrike, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CriticalShot, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Dodge, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Counter, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Healer, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Alchemist, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Energist, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Chemist, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Hammersmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Spellsmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Bowsmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Swordsmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Weaver, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Tanner, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Scalesmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Platesmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Goldsmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Shieldsmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Hammerbane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Spellbane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Bowbane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Swordbane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Threadbare, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(StudRemover, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Scalebane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Platebane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Goldbane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Shieldbane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Holy, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Fire, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Ice, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Shock, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Dark, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Light, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Force, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Mind, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Earth, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Blood, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Flesh, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Wind, Gecko::CharacterSkillData)
    ;
    PyBindVector<Gecko::CharacterSkillDataArray>(m, "CharacterSkillDataArray");

    // CharacterStatChangeData.h
    PyBindClass<Gecko::CharacterStatChangeData>(m, "CharacterStatChangeData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_SIMPLE(UpdateAvailableChanges, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_POLICY(GetPassiveChanges, Gecko::CharacterStatChangeData, PyBindReturnCopy)
        WRAPPING_ADD_METHOD_POLICY(GetActiveChanges, Gecko::CharacterStatChangeData, PyBindReturnCopy)
        WRAPPING_ADD_METHOD_POLICY(GetActionableChanges, Gecko::CharacterStatChangeData, PyBindReturnCopy)
        WRAPPING_ADD_METHOD_SIMPLE(AddProlongedStatChange, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_SIMPLE(RemoveProlongedStatChange, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_OVERLOADED_POLICY(GetProlongedStatChange, Gecko::CharacterStatChangeData, PyBindReturnRefInternal, const Gecko::String&)
        WRAPPING_ADD_METHOD_OVERLOADED_POLICY_CONST(GetProlongedStatChange, Gecko::CharacterStatChangeData, PyBindReturnCopy, const Gecko::String&)
        WRAPPING_ADD_METHOD_SIMPLE(GetProlongedStatChangeEntries, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_SIMPLE(DoesProlongedStatChangeExist, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_SIMPLE(HasProlongedStatChangeExpired, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_SIMPLE(RemoveAllExpiredProlongedStatChanges, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PassiveSkillDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PassiveItemDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActiveSkillDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActiveItemDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionableSkillDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionableItemDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ProlongedStatChanges, Gecko::CharacterStatChangeData)
    ;
    PyBindVector<Gecko::CharacterStatChangeDataArray>(m, "CharacterStatChangeDataArray");

    // CharacterMediaData.h
    PyBindClass<Gecko::CharacterMediaData>(m, "CharacterMediaData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterMediaData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PortraitImage, Gecko::CharacterMediaData)
    ;
    PyBindVector<Gecko::CharacterMediaDataArray>(m, "CharacterMediaDataArray");
}
