// Fyleria Engine
// Copyright © 2016 Go Go Gecko Productions

#include "Character/Character.h"
#include "Character/CharacterGenerator.h"
#include "Character/CharacterManager.h"
#include "Character/CharacterTypes.h"
#include "Utility/Macros.h"
#include "Utility/TypesPython.h"

namespace Gecko
{

CharacterManager* GetCharacterManager() { return CharacterManager::GetInstance(); }

};

PYBIND11_MAKE_OPAQUE(Gecko::CharacterGeneratorList);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterList);

PYBIND11_EMBEDDED_MODULE(GeckoCharacter, m)
{
    // CharacterGenerator.h
    PyBindClass<Gecko::CharacterGenerator, Gecko::SerializableToJson>(m, "CharacterGenerator")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FirstName, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(LastName, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FirstNamePattern, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(LastNamePattern, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AgeStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AgeEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Gender, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Hair, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Eyes, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Handedness, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BaseRace, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(TransformedRace, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PowerSet, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(UseRandomName, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(UseRandomGender, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(UseRandomHair, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(UseRandomEyes, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(UseRandomHandedness, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(UseRandomBaseRace, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(UseRandomTransformedRace, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(UseRandomPowerSet, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HPStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HPEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MPStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MPEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EPStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EPEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HPRegenStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HPRegenEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MPRegenStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MPRegenEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EPRegenStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EPRegenEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SpeedStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SpeedEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BluntATKStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BluntATKEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BluntDEFStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BluntDEFEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PierceATKStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PierceATKEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PierceDEFStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PierceDEFEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashATKStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashATKEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashDEFStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashDEFEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyATKStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyATKEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyDEFStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyDEFEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicATKStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicATKEnd, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicDEFStart, Gecko::CharacterGenerator)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicDEFEnd, Gecko::CharacterGenerator)
    ;
    PyBindVector<Gecko::CharacterGeneratorList>(m, "CharacterGeneratorList");
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterGeneratorToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterGeneratorListToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterGeneratorFromJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterGeneratorListFromJsonString, Gecko);

    // Character.h
    PyBindClass<Gecko::Character>(m, "Character")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(RegenerateCharacterData, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(OnBattleStarted, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(OnBattleEnded, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(OnBattleTally, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(OnBattleFullyCompleted, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(OnBattleRoundAdvanced, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(OnBattleGivingDamage, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(OnBattleTakingDamage, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(OnBattleChoosingTargets, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(OnBattleBecomingTarget, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(OnBattleActionAttackSetup, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(OnBattleActionDefendSetup, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(OnBattleActionFinished, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(GetBoolStatValue, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(GetIntStatValue, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(GetFloatStatValue, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(GetStringStatValue, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(GetStringListStatValue, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(SetBoolStatValue, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(SetIntStatValue, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(SetFloatStatValue, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(SetStringStatValue, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(SetStringListStatValue, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(ResolveTargetPlaceholder, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(ResolveTargetPlaceholders, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(GetEquippedItemTypeCount, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(GetEquippedWeaponCount, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(GetEquippedShieldCount, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(CanAddEquippedItem, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(CanRemoveEquippedItem, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(AddEquippedItem, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(RemoveEquippedItem, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(GetHandInfoByWeaponSet, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(AddProlongedStatChange, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(RemoveProlongedStatChange, Gecko::Character)
        WRAPPING_ADD_METHOD_OVERLOADED_POLICY(GetProlongedStatChange, Gecko::Character, PyBindReturnRefInternal, const Gecko::IndexedString&)
        WRAPPING_ADD_METHOD_OVERLOADED_POLICY_CONST(GetProlongedStatChange, Gecko::Character, PyBindReturnCopy, const Gecko::IndexedString&)
        WRAPPING_ADD_METHOD_SIMPLE(GetProlongedStatChangeEntries, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(DoesProlongedStatChangeExist, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(HasProlongedStatChangeExpired, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(RemoveAllExpiredProlongedStatChanges, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(AddSkillUse, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(GetSkillUseCount, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(SetAllSkillCurrentValues, Gecko::Character)
        WRAPPING_ADD_METHOD_SIMPLE(SetAllSkillRankingValues, Gecko::Character)
        WRAPPING_ADD_METHOD_POLICY(GetPassiveChanges, Gecko::Character, PyBindReturnCopy)
        WRAPPING_ADD_METHOD_POLICY(GetActiveChanges, Gecko::Character, PyBindReturnCopy)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(FirstName, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(LastName, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Age, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Gender, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Hair, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Eyes, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Handedness, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(BaseRace, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(TransformedRace, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PowerSet, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(EquippedItems, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CurrentWeaponSet, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BarbarianCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BarbarianRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MageCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MageRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RogueCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RogueRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BlademasterCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BlademasterRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AvatarCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AvatarRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AmbidextrousCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AmbidextrousRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FocusedCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FocusedRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StalwartCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StalwartRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SeverCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SeverRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SliceCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SliceRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlitCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlitRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CleaveCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CleaveRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DecapitateCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DecapitateRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ParryCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ParryRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RiposteCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RiposteRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BashCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BashRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SmashCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SmashRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CrushCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CrushRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ImpactCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ImpactRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BreakCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BreakRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CrackCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CrackRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BlockCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BlockRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RushCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RushRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PierceCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PierceRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DrillCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DrillRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShootCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShootRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ImpaleCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ImpaleRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StealthStrikeCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StealthStrikeRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CriticalShotCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CriticalShotRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DodgeCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DodgeRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CounterCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CounterRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HealerCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HealerRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AlchemistCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AlchemistRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergistCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergistRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ChemistCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ChemistRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HammersmithCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HammersmithRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SpellsmithCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SpellsmithRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BowsmithCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BowsmithRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SwordsmithCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SwordsmithRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WeaverCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WeaverRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(TannerCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(TannerRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ScalesmithCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ScalesmithRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PlatesmithCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PlatesmithRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GoldsmithCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GoldsmithRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShieldsmithCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShieldsmithRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HammerbaneCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HammerbaneRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SpellbaneCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SpellbaneRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BowbaneCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BowbaneRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SwordbaneCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SwordbaneRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ThreadbareCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ThreadbareRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StudRemoverCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StudRemoverRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ScalebaneCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ScalebaneRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PlatebaneCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PlatebaneRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GoldbaneCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GoldbaneRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShieldbaneCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShieldbaneRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HolyCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HolyRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FireCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FireRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(IceCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(IceRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShockCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShockRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DarkCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DarkRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(LightCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(LightRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ForceCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ForceRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MindCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MindRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EarthCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EarthRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BloodCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BloodRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FleshCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FleshRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WindCurrent, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WindRank, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ProgressDataBase, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ProgressDataPassives, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ProgressDataActives, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(BattleDataBase, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(BattleDataPassives, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(BattleDataActives, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PreviousActionTypes, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PassiveSkillDataList, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActiveSkillDataList, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionableSkillDataList, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PassiveItemDataList, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActiveItemDataList, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionableItemDataList, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(AvailableActions, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ProlongedStatChanges, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AttackCounter, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DefendCounter, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CharacterID, Gecko::Character)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CharacterTargetType, Gecko::Character)
    ;
    PyBindVector<Gecko::CharacterList>(m, "CharacterList");
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterListToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterFromJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterListFromJsonString, Gecko);

    // CharacterManager.h
    PyBindClass<Gecko::CharacterManager>(m, "CharacterManager")
        WRAPPING_ADD_METHOD_SIMPLE(LoadCharacter, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(LoadCharacterFromFile, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(SaveCharacterToFile, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(CreateCharacter, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(UnloadCharacter, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(DoesCharacterExist, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(GenerateCharacter, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_OVERLOADED_POLICY(GetCharacter, Gecko::CharacterManager, PyBindReturnRefInternal, const Gecko::IndexedString&)
        WRAPPING_ADD_METHOD_OVERLOADED_POLICY_CONST(GetCharacter, Gecko::CharacterManager, PyBindReturnCopy, const Gecko::IndexedString&)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyStatChange, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyStatChangeEntry, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_OVERLOADED(ApplyStatChangeEntryOperation, Gecko::CharacterManager, const Gecko::IndexedString&, const Gecko::IndexedString&, const Gecko::IndexedString&, const Gecko::IndexedString&, Gecko::Float)
        WRAPPING_ADD_METHOD_OVERLOADED(ApplyStatChangeEntryOperation, Gecko::CharacterManager, const Gecko::IndexedString&, const Gecko::IndexedString&, const Gecko::IndexedString&, const Gecko::IndexedString&, Gecko::Int)
        WRAPPING_ADD_METHOD_OVERLOADED(ApplyStatChangeEntryOperation, Gecko::CharacterManager, const Gecko::IndexedString&, const Gecko::IndexedString&, const Gecko::IndexedString&, const Gecko::IndexedString&, Gecko::Bool)
        WRAPPING_ADD_METHOD_OVERLOADED(ApplyStatChangeEntryOperation, Gecko::CharacterManager, const Gecko::IndexedString&, const Gecko::IndexedString&, const Gecko::IndexedString&, const Gecko::IndexedString&, const Gecko::IndexedString&)
        WRAPPING_ADD_METHOD_OVERLOADED(ApplyStatChangeEntryOperation, Gecko::CharacterManager, const Gecko::IndexedString&, const Gecko::IndexedString&, const Gecko::IndexedString&, const Gecko::IndexedString&, const Gecko::IndexedStringList&)
        WRAPPING_ADD_METHOD_SIMPLE(DoesStatChangeEntryUseDelta, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsStatFloat, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsStatInt, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsStatBool, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsStatString, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsStatStringList, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(GetSourceStatChangeEntryValues, Gecko::CharacterManager)
        WRAPPING_ADD_METHOD_SIMPLE(GetDestStatChangeEntryValues, Gecko::CharacterManager)
    ;

    // CharacterTypes.h
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterEquipmentTypeToCharacterWeaponSetType, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterTargetTypeToCharacterPartyType, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertItemTypeToCharacterActionType, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertItemTypeToCharacterEquipTypes, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertSkillWeaponBaseTypeToCharacterActionType, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertSkillWeaponTypeToCharacterActionType, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterTreeIndexTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterSegmentTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterProgressStatTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterBattleStatTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterStatusTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterBaseRaceTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterTransformedRaceTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterPowerSetTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterWeaponSetTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterGenderTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterHairTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterEyeTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterHandednessTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterHandTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterEquipmentTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterTargetTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterPartyTypeNames, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterActionTypeNames, Gecko);

    // Local
    WRAPPING_STANDALONE_METHOD_POLICY(GetCharacterManager, Gecko, PyBindReturnAutoRef);
}
